import type { SidebarItem } from '@/components/Sidebar.tsx'
import {
  Activity,
  Ambulance,
  BadgeCheck,
  Bed,
  Bell,
  Camera,
  ChartNoAxesCombined,
  ClipboardCheck,
  Building2,
  Calendar,
  ClipboardList,
  FileClock,
  FilePlus,
  CreditCard,
  Droplets,
  FileText,
  FlaskConical,
  HandHeart,
  HeartPulse,
  LayoutDashboard,
  Lock,
  LogIn,
  MapPinned,
  Mic,
  NotebookText,
  Package,
  ParkingCircle,
  Pill,
  ShieldAlert,
  ShoppingCart,
  Shield,
  ShieldCheck,
  Sparkles,
  Star,
  Stethoscope,
  Syringe,
  Trophy,
  Truck,
  UserPlus,
  Users,
  UtensilsCrossed,
  Video,
} from 'lucide-react'

export const adminSidebar: SidebarItem[] = [
  { to: '/admin', label: 'Dashboard', icon: LayoutDashboard },
  { to: '/admin/doctors', label: 'Doctors', icon: Stethoscope },
  { to: '/admin/patients', label: 'Patients', icon: Users },
  { to: '/admin/departments', label: 'Departments', icon: Building2 },
  { to: '/admin/staff', label: 'Staff', icon: UserPlus },
  { to: '/admin/appointments', label: 'Appointments', icon: Calendar },
  { to: '/admin/medicines', label: 'Medicines', icon: Pill },
  { to: '/admin/lab-tests', label: 'Lab Tests', icon: FlaskConical },
  { to: '/admin/blood', label: 'Blood Bank', icon: Droplets },
  { to: '/admin/rooms', label: 'Rooms', icon: Building2 },
  { to: '/admin/beds', label: 'Beds', icon: Bed },
  { to: '/admin/ambulances', label: 'Ambulances', icon: Ambulance },
  { to: '/admin/blog', label: 'Blog', icon: FileText },
  { to: '/admin/payroll', label: 'Payroll', icon: CreditCard },
  { to: '/admin/inventory-alerts', label: 'Inventory Alerts', icon: Bell },
  { to: '/admin/audit-logs', label: 'Audit Logs', icon: FileText },
  { to: '/admin/branches', label: 'Branches', icon: Building2 },
  { to: '/admin/permissions', label: 'Permissions', icon: Lock },
  { to: '/admin/trauma-alerts', label: 'Trauma Alerts', icon: ShieldAlert },
  { to: '/admin/branding-settings', label: 'Branding', icon: Sparkles },
  { to: '/admin/owner-analytics', label: 'Owner Analytics', icon: Activity },
  { to: '/admin/clinic-management', label: 'Clinics', icon: Building2 },
  { to: '/admin/staff-attendance', label: 'Attendance', icon: ClipboardCheck },
  { to: '/admin/insurance-claims', label: 'Insurance Claims', icon: Shield },
  { to: '/admin/operation-theatre', label: 'Operation Theatre', icon: Calendar },
  { to: '/admin/organ-transplant', label: 'Transplant Registry', icon: HeartPulse },
  { to: '/admin/monthly-reports', label: 'Monthly Reports', icon: FilePlus },
  { to: '/admin/doctor-ranking', label: 'Doctor Ranking', icon: Trophy },
  { to: '/admin/demographics', label: 'Demographics', icon: ChartNoAxesCombined },
  { to: '/admin/financial-year-report', label: 'FY Report', icon: Activity },
  { to: '/admin/two-factor', label: 'Two-Factor Setup', icon: ShieldCheck },
  { to: '/admin/compliance', label: 'Compliance', icon: FileClock },
  { to: '/admin/canteen', label: 'Canteen', icon: UtensilsCrossed },
  { to: '/admin/parking', label: 'Parking', icon: ParkingCircle },
]

export const doctorSidebar: SidebarItem[] = [
  { to: '/doctor', label: 'Dashboard', icon: LayoutDashboard },
  { to: '/doctor/patients', label: 'Patients', icon: Users },
  { to: '/doctor/prescriptions', label: 'Prescriptions', icon: ClipboardList },
  { to: '/doctor/schedule', label: 'Schedule', icon: Calendar },
  { to: '/doctor/leave', label: 'Leave', icon: FileText },
  { to: '/doctor/analytics', label: 'Analytics', icon: Activity },
  { to: '/doctor/prescription-templates', label: 'Templates', icon: NotebookText },
  { to: '/doctor/symptom-checker', label: 'Symptom Checker', icon: BadgeCheck },
  { to: '/doctor/telemedicine', label: 'Telemedicine', icon: Mic },
  { to: '/doctor/referrals', label: 'Referrals', icon: HandHeart },
  { to: '/doctor/dicom-viewer', label: 'DICOM Viewer', icon: Camera },
  { to: '/doctor/video-call', label: 'Video Call', icon: Video },
]

export const patientSidebar: SidebarItem[] = [
  { to: '/patient', label: 'Dashboard', icon: LayoutDashboard },
  { to: '/patient/appointments', label: 'Appointments', icon: Calendar },
  { to: '/patient/medical-history', label: 'Medical History', icon: FileText },
  { to: '/patient/lab-reports', label: 'Lab Reports', icon: FlaskConical },
  { to: '/patient/bills', label: 'Bills', icon: CreditCard },
  { to: '/patient/profile', label: 'Profile', icon: Users },
  { to: '/patient/notifications', label: 'Notifications', icon: Bell },
  { to: '/patient/health-tracker', label: 'Health Tracker', icon: Activity },
  { to: '/patient/medicine-reminders', label: 'Medicine Reminders', icon: Pill },
  { to: '/patient/insurance', label: 'Insurance', icon: ShieldAlert },
  { to: '/patient/vaccinations', label: 'Vaccinations', icon: Syringe },
  { to: '/patient/insurance-claims', label: 'Claims', icon: Shield },
  { to: '/patient/feedback', label: 'Feedback', icon: Star },
  { to: '/patient/video-call', label: 'Video Call', icon: Video },
  { to: '/patient/access-logs', label: 'Access Logs', icon: FileClock },
  { to: '/patient/canteen', label: 'Canteen Order', icon: UtensilsCrossed },
]

export const receptionistSidebar: SidebarItem[] = [
  { to: '/receptionist', label: 'Dashboard', icon: LayoutDashboard },
  { to: '/receptionist/register-patient', label: 'Register Patient', icon: UserPlus },
  { to: '/receptionist/book-appointment', label: 'Book Appointment', icon: Calendar },
  { to: '/receptionist/check-in', label: 'Check In', icon: LogIn },
  { to: '/receptionist/billing', label: 'Billing', icon: CreditCard },
  { to: '/receptionist/admit-discharge', label: 'Admit / Discharge', icon: Bed },
  { to: '/receptionist/queue-tokens', label: 'Queue Tokens', icon: Users },
]

export const laboratorySidebar: SidebarItem[] = [
  { to: '/laboratory', label: 'Dashboard', icon: LayoutDashboard },
  { to: '/laboratory/tests', label: 'Tests', icon: FlaskConical },
  { to: '/laboratory/pending', label: 'Pending Reports', icon: ClipboardList },
  { to: '/laboratory/completed', label: 'Completed Reports', icon: FileText },
]

export const pharmacistSidebar: SidebarItem[] = [
  { to: '/pharmacist', label: 'Dashboard', icon: LayoutDashboard },
  { to: '/pharmacist/medicines', label: 'Medicines', icon: Pill },
  { to: '/pharmacist/suppliers', label: 'Suppliers', icon: Truck },
  { to: '/pharmacist/purchases', label: 'Purchases', icon: ShoppingCart },
  { to: '/pharmacist/sales', label: 'Sales', icon: Package },
  { to: '/pharmacist/alerts', label: 'Stock Alerts', icon: Bell },
  { to: '/pharmacist/interactions', label: 'Interactions', icon: MapPinned },
]
